title:            ГБУЗ РЕСПУБЛИКИ КАРЕЛИЯ "РЕСПУБЛИКАНСКИЙ ПЕРИНАТАЛЬНЫЙ ЦЕНТР ИМ. ГУТКИНА К.А."
title_small:      ГБУЗ "РПЦ им. Гуткина К.А."
title_address:    Республика Карелия, г. Петрозаводск, ул. Сыктывкарская, д. 9
title_phone_1:    Приемная главного врача<br>8(8142) 333-111
title_phone_2:    Голосовое меню<br>8(8142) 333-112
description:      НЕофициальный сайт ГБУЗ РЕСПУБЛИКИ КАРЕЛИЯ "РЕСПУБЛИКАНСКИЙ ПЕРИНАТАЛЬНЫЙ ЦЕНТР ИМ. ГУТКИНА К.А."
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:    https://panikptz.github.io
# url:  http://192.168.15.143:4000
url:

# Owner/author information
owner:
  name:           Пазий Андрей
  avatar:         ico_telephone.jpg
  bio:            "Регистратура Консультативно-диагностического отделения: 8905-299-97-16, 8(8142)333-115<br><br>Приемный покой:<br>8905-299-97-12, 8(8142)333-113<br><br>Отделение лучевой и магнитно-резонансной диагностики:<br>8(8142)333-111 доб. 1138<br><br>Пост родового отделения:<br>8905-299-97-19,<br>8(8142)333-111,<br>доб. 5025 или доб. 5026"
  email:          rpc@zdrav10.ru
  

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-39365944-4
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Moscow
future:      true
# pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title
permalink:    /news/:year/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  # coderay:
  #   coderay_line_numbers: 
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

collections:
  structure:
    output: true
  staff:
    output: false
  covid19:
    output: true
  docs:
    output: true
    # Почему-то указанная здесь сортировака не работает на Github pages.
    # Поэтому указываю сортировку в каждом файле сотрудника и обрабатываю ее в _\layouts\department.html
    # sort_by: order

defaults:
  - scope:
      path: ""
      type: "structure"
    values:
      layout: "department"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
