title:            ГБУЗ РЕСПУБЛИКИ КАРЕЛИЯ<br>"РЕСПУБЛИКАНСКИЙ ПЕРИНАТАЛЬНЫЙ ЦЕНТР"
title_small:      ГБУЗ РПЦ
title_address:    Республика Карелия, г. Петрозаводск, ул. Сыктывкарская, д. 9
title_phone_1:    Приемная главного врача<br>8(8142) 333-111
title_phone_2:    Голосовое меню<br>8(8142) 333-112
title_rodi:       С 1 января 2021 года<br>809 родов&nbsp;&nbsp;455 мальчиков&nbsp;&nbsp;396 девочек&nbsp;&nbsp;16 двоен
tagline:          Life without Pants!
description:      An awesome Jekyll theme by Engineer Hossain Mohd Faysal featuring a slide out drawer navigation for mobile browsers.
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:    https://panikptz.github.io
# url:  http://192.168.15.143:4000
url:

# Owner/author information
owner:
  name:           
  avatar:         ico_telephone.jpg
  bio:            "Регистратура Консультативно-диагностического отделения: 8905-299-97-16, 8(8142)333-115<br><br>Приемный покой:<br>8905-299-97-12, 8(8142)333-113<br><br>Отделение лучевой и магнитно-резонансной диагностики:<br>8(8142)333-111 доб. 1138<br><br>Пост родового отделения:<br>8905-299-97-19,<br>8(8142)333-111,<br>доб. 5025 или доб. 5026"
  email:          rpc@zdrav10.ru
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        
  facebook:       
  github:         
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  hmfaysalsocial: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-39365944-4
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
# links:
#   - title: Главная
#     url: /
#   - title: Новости
#     url: /news/
#   - title: Информация для пациентов
#     url: /articles/
#   - title: Структура центра
#     url: /about/
#   - title: Платные услуги
#     url: /technical-details/
#   - title: О нас
#     url: /about/
#   - title: Задать вопрос
#     url: /about/
  # - title: Setup
  #   url: /theme-setup/
  # - title: T-Details
  #   url: /technical-details/
  # - title: The Evil-Genius
  #   url: http://www.theevilgenius.tk/
    # external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Moscow
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title
permalink:    /news/:year/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  # coderay:
  #   coderay_line_numbers: 
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

collections:
  structure:
    output: true

defaults:
  - scope:
      path: ""
      type: "structure"
    values:
      layout: "page"